version: '3'
services:
  # MongoDB container
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    ports:
      - 27021:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
   

  # PostgreSQL container
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_user_password
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


